apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sail.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "sail.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "sail.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}