{{- if .Values.controller.gatewayClassResource.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  labels:
    {{- include "sail.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.controller.gatewayClassResource.name }}
spec:
  controllerName: {{ .Values.controller.gatewayClassResource.controllerValue }}
{{- end }}