apiVersion: v1
kind: Service
metadata:
  name: {{ include "sail.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
  - name: http
    port: {{ .Values.controller.service.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.controller.service.targetPorts.http }}
  selector:
    {{- include "sail.selectorLabels" . | nindent 4 }}
