apiVersion: v1
kind: Service
metadata:
  name: yarp-controller
  namespace: yarp
spec:
  ports:
  - name: api
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ingress-yarp-controller
  type: ClusterIP