apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bar-route
spec:
  parentRefs:
  - name: sail
  hostnames:
  - "foo.bar.com"
  rules:
  - matches:
     - path:
        type: PathPrefix
        value: /login
    backendRefs:
    - name: backend-sail
      port: 8085