controller:
  name: controller
  image:
    registry: docker.io
    image: inendless/ingress-controller
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  containerName: controller  
  containerPort:
    http: 80
    https: 443  
    
  scope:
    enabled: false
    namespace: ""
    namespaceSelector: ""

  hostPort:
    enabled: false
    ports:
      http: 80
      https: 443

  ingressClassResource:
    name: sail-controller
    ingressClass: sail
    enabled: true
    controllerValue: inendless.com/ingress-sail
    parameters: {}

  livenessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
      scheme: HTTP

  resources:
    requests:
      cpu: 100m
      memory: 90Mi    

  podSecurityContext: {}
  podAnnotations: {}
  containerSecurityContext: {}

  tolerations: []
  nodeSelector: {}
  affinity: {}
  sysctls: {}
  autoscaling:
    enabled: false   
  
  replicaCount: 1 

  service:
   enabled: true
   ports:
      http: 80
      https: 443
   targetPorts:
      http: http
      https: https
   type: LoadBalancer     
 
proxy:
  enabled: true
  kind: DaemonSet
  name: proxy
  containerName: proxy
  image:
    registry: docker.io
    image: inendless/sail-proxy
    tag: "1.0.0"
    pullPolicy: IfNotPresent  

  containerPort:
    http: 80
    https: 443      
  
  hostPort:
    enabled: false
    ports:
      http: 80
      https: 443

  autoscaling:
    enabled: false    

  replicaCount: 1 
  
  service:
   enabled: true
   ports:
      http: 80
      https: 443
   targetPorts:
      http: http
      https: https
   type: LoadBalancer     

  livenessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
      scheme: HTTP

  podAnnotations: {}

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true
  annotations: {}