apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sail-ingress
spec:
  ingressClassName: sail-controller
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
