controller:
  scope:
    enabled: false
    namespace: ""
    namespaceSelector: ""
  ingressClassResource:
   name: sail-controller
   ingressClass: sail
   enabled: true
   controllerValue: "inendless.com/ingress-sail"
   parameters: {}

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true
  annotations: {}